id: BASE
type: BIOME
abstract: true
extends:
  - DEPOSITS_DEFAULT
  - ORES_DEFAULT

slant-depth: 15

ocean:
  palette: BLOCK:minecraft:water
  level: 62

features:
  global-preprocessors:
    - LAVA_FLOOR
    - UNDERGROUND_LAVA_COLUMNS
    - CONTAIN_FLOATING_WATER
    - CAVE_GLOW_LICHEN
#    - GRASS_PLATFORMS
#    - TEXTURED_DIORITE_SLANT
#    - TEXTURED_GRANITE_SLANT
#    - TEXTURED_ANDESITE_SLANT
    - TEXTURED_STONE_SLANT
  underwater-flora:
    - KELP
    - SEAGRASS
