name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  release-docs:
    runs-on: ubuntu-latest
    env:
      WIKI_DIRECTORY: .wiki # Contents of this directory get pushed to the wiki
      WIKI_PARENT_REPOSITORY: ${{ github.repository }} # Where to publish to

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate Biome List 
        run: bash ./.scripts/generate-biome-list.sh

      - name: Upload Documentation to Wiki
        run: sh ./.scripts/upload-to-wiki.sh 
        env:
          LOGIN_NAME: ${{ secrets.GH_ACTIONS_COMMIT_NAME }} 
          LOGIN_EMAIL: ${{ secrets.GH_ACTIONS_COMMIT_EMAIL }} 
          ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  release:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
      CHANGELOG: CHANGELOG.md
      RELEASE_CHANGELOG: RELEASE_CHANGELOG.md
      START_REGEX: "^## \\[Unreleased\\]"
      END_REGEX: "^## "
      PACK_ARTIFACT_NAME: default

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Validate Biome Colors
        run: sh ./.scripts/validate-biome-colors.sh

      - name: Check for version bump
        run: sh ./.scripts/check-version-bump.sh

      - name: Create artifacts
        run: sh ./.scripts/pack.sh

      - name: Grab release changelog
        if: env.version-bumped == 'true'
        run: sh ./.scripts/grab-release-changelog.sh

      - name: Update changelog
        if: env.version-bumped == 'true'
        run: sh ./.scripts/update-changelog.sh

      - name: Push changelog
        if: env.version-bumped == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ secrets.GH_ACTIONS_COMMIT_NAME }} 
          author_email: ${{ secrets.GH_ACTIONS_COMMIT_EMAIL }} 
          message: Version ${{ env.version }}
          tag: v${{ env.version }} -F ${{ env.release_changelog }} --cleanup=verbatim
          add: ${{ env.changelog }}

      - name: Release
        if: env.version-bumped == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          body_path: ${{ env.release_changelog }}
          files: |
            .artifacts/*

      - name: Release latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            .artifacts/*

