name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Release Script
        run: sh ./post-commit.sh
