name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      repo_url: ${{ github.server_url }}/${{ github.repository }}
      changelog: CHANGELOG.md
      new_changelog: CHANGELOG_NEW.md
      start_regex: "^## \\[Unreleased\\]"
      end_regex: "^## "
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
  
      - name: check-version-bump
        run: sh ./scripts/check-version-bump.sh

      - name: create-artifacts
        run: zip -r ./overworld.zip *

      - name: grab-new-changelog
        run: sh ./scripts/grab-new-changelog.sh
        if: env.version-bumped == 'true'

      - name: update-changelog
        run: sh ./scripts/update-changelog.sh
        if: env.version-bumped == 'true'

      - name: push-update-changelog
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Version ${{ env.version }}
          tag: v${{ env.version }} -F ${{ env.new_changelog }} --cleanup=verbatim
          add: CHANGELOG.md
        if: env.version-bumped == 'true'

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          body_path: ${{ env.new_changelog }}
          files: |
            overworld.zip
        if: env.version-bumped == 'true'

      - name: release-latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            overworld.zip

