name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Create Artifacts
        run: zip -r ./overworld.zip *
      - name: Check Version Bump
        run: sh ./check-version-bump.sh
      - name: Update Changelog
        if: env.VERSION_BUMPED == 'true'
        run: sh ./update-changelog.sh
      - name: Push New Changelog
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          body_path: CHANGELOG_NEW.md
          files: |
            overworld.zip
