name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    outputs:
      version-bumped: ${{ steps.check-version-bump.outputs.version-bumped }}
      previous-version: ${{ steps.check-version-bump.outputs.previous-version }}
      version: ${{ steps.check-version-bump.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Check version bump
        id: check-version-bump
        run: sh ./check-version-bump.sh

  release:
    runs-on: ubuntu-latest
    needs: check-version-bump
    #if: ${{ needs.check-version-bump.outputs.version-bumped == 'true' }}
    #env:
    #  version: ${{ needs.check-version-bump.outputs.version }}
    #  previous_version: ${{ needs.check-version-bump.outputs.previous-version }}
    #  changelog: CHANGELOG.md
    #  new_changelog: CHANGELOG_NEW.md
    steps:
      - run: echo ${{ needs.check-version-bump.outputs.version-bumped }}
    #  - name: create-artifacts
    #    run: zip -r ./overworld.zip *
    #  - name: update-changelog
    #    run: sh ./update-changelog.sh
    #  - name: push-new-changelog
    #    uses: EndBug/add-and-commit@v9
    #    with:
    #      default_author: github_actions
    #      add: CHANGELOG.md
    #  - name: release
    #    uses: softprops/action-gh-release@v1
    #    with:
    #      tag_name: v${{ env.version }}
    #      body_path: ${{ env.new_changelog }}
    #      files: |
    #        overworld.zip
